name: Auto Close PR on build.yml Change

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  auto-close:
    runs-on: ubuntu-latest

    steps:
      - name: Check out PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check if .github/workflows/main.yml was changed
        id: check_files
        run: |
          # Fetch the base branch to compare
          git fetch origin ${{ github.event.pull_request.base.ref }}

          # Check for changes in main.yml between PR and base branch
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD | grep -q "^.github/workflows/main.yml$"; then
            echo "file_changed=true" >> $GITHUB_ENV
          else
            echo "file_changed=false" >> $GITHUB_ENV
          fi

      - name: Close PR if main.yml changed
        if: env.file_changed == 'true'
        uses: peter-evans/close-pull-request@v4
        with:
          comment: |
            This pull request is being automatically closed because it includes changes to the workflow file `.github/workflows/main.yml`.
